"""modified tables

Revision ID: 8aff35488d21
Revises: 
Create Date: 2023-11-24 23:15:17.973190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aff35488d21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=False),
    sa.Column('last_name', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phone_number', sa.Unicode(length=255), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=45), nullable=False),
    sa.Column('incident_type', sa.String(length=45), nullable=False),
    sa.Column('product', sa.String(length=45), nullable=False),
    sa.Column('product_category', sa.String(length=45), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_attachments', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_incident_type'), ['incident_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_product'), ['product'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_product_category'), ['product_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_title'), ['title'], unique=False)

    op.create_table('updated_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_ticket_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_attachments', sa.String(length=45), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['original_ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('updated_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_updated_ticket_description'), ['description'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('updated_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_updated_ticket_description'))

    op.drop_table('updated_ticket')
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_title'))
        batch_op.drop_index(batch_op.f('ix_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_ticket_product_category'))
        batch_op.drop_index(batch_op.f('ix_ticket_product'))
        batch_op.drop_index(batch_op.f('ix_ticket_incident_type'))
        batch_op.drop_index(batch_op.f('ix_ticket_description'))

    op.drop_table('ticket')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
